name: Daily Experiment Publisher

on:
  schedule:
    - cron: '0 14 * * *'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "Workflow is running successfully"
